### ISSUE TITLE
flickering

### ISSUE THREAD

**Issue by trusktr** [PerBothner/DomTerm#49]
The rendering seems is flickery and leaving various colors behind in some cells, especially while inside of NeoVim (alternate buffer). Is there some things to configure to make it render better? Or is it a known issue that needs work?

**Comment by trusktr** [comment]
example:

![flicker](https://user-images.githubusercontent.com/297678/47983283-a9df7180-e087-11e8-829a-7bd249b3d4ab.gif)

**Comment by trusktr** [comment]
Another thing is that the cursor seems misaligned when stuff is rendered at the right side of the command prompt.

For example, here's what my terminal looks like in iTerm:

<img width="1452" alt="screen shot 2018-11-04 at 11 26 32 pm" src="https://user-images.githubusercontent.com/297678/47983793-4d7d5180-e089-11e8-89d6-fbd685edf3e3.png">

On the right side, the blue dots represent the status of git.

In DomTerm, the cursor seems to be misaligned and chops the command prompt, and the dot on the right side is not all the way flush to the right:

<img width="1381" alt="screen shot 2018-11-04 at 11 29 36 pm" src="https://user-images.githubusercontent.com/297678/47983852-80bfe080-e089-11e8-94da-3e1a3265e654.png">

As you can see the cursor is on top of the `❯` mark.

---

Another thing that happens is syntax highlight doesn't always update (same issue as with colors staying behind in NeoVim I suppose).

For example, in iTerm:

<img width="315" alt="screen shot 2018-11-04 at 11 31 23 pm" src="https://user-images.githubusercontent.com/297678/47983943-cc728a00-e089-11e8-9526-80c785db7831.png">

and in DomTerm:

<img width="340" alt="screen shot 2018-11-04 at 11 31 37 pm" src="https://user-images.githubusercontent.com/297678/47983954-d1cfd480-e089-11e8-8fa8-9d6eec58880f.png">

**Comment by trusktr** [comment]
I love DomTerm though. It will be awesome when these issues are solved!

**Comment by trusktr** [comment]
Interestingly, just about every other terminal I've tried in Atom has the same issue of the cursor being in the wrong place, on top of the command line text.

**Comment by albertz** [comment]
Btw, I also tried [GraphTerm](https://github.com/mitotic/graphterm) (very similar project to DomTerm), and these render issues do not appear there (because of that, it's currently somewhat more usable for me now). But maybe it helps to look a bit at their code and compare what they do different.

**Comment by lypanov** [comment]
I'm also seeing these issues with "lagging colors" with alot an email client. This makes knowing which email is currently selected impossible alas.

**Comment by lypanov** [comment]
I'm also seeing many different issues with powershell. Everything from missing colors during command entry, to seeming race conditions in execution itself (typing, pressing enter, result -> nothing, command not even in history).

**Comment by PerBothner** [comment]
I have little-to-no powershell experience.  If you could tell me precise steps to reproduce the problems (included expected behaviour vs observed behavior) I can try to reproduce (and hopefully debug) it.

**Comment by lypanov** [comment]
Example reproducable rendering issue for Powershell / WSL / Electron: Start "pwsh". Hold paste down for the text `blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah`. After a short while the text will begin to show with a different background color, press return straight away.

Expected behavior: the predictive echo text should remain, instead, it seemingly is gone. History is correct - the part after the background color change is actually executed, but, it's gone from the screen.

Ah, a clue: resizing the window seems to fix the rendering. The missing text reappears.

Frequently after performing this exercise a few times DomTerm gets in a really weird state, pressing return results in DomTerm scrolling up to the top of the scroll buffer. With the exception of scrolling nothing I do results in any visible reaction in the terminal. It's as if DomTerm lost connection.

My JS console has the following error in this situation:

```
Uncaught TypeError: Cannot read property 'offsetTop' of null
    at Terminal._adjustPauseLimit (terminal.js:7893)
    at Terminal.keyPressHandler (terminal.js:8072)
    at HTMLDivElement.<anonymous> (terminal.js:3215)
```

Another such stacktrace
```
Uncaught TypeError: Cannot read property '_widthColumns' of undefined
    at Terminal.deleteCharactersRight (terminal.js:4733)
    at Terminal.insertSimpleOutput (terminal.js:6935)
    at DTParser.insertString (domterm-parser.js:404)
    at Terminal.insertString (terminal.js:6062)
    at Terminal.insertBytes (terminal.js:6008)
    at Object.DomTerm._handleOutputData (terminal.js:8304)
    at WebSocket.wsocket.onmessage (terminal.js:8413)
```

In yet another case I get the above widthColumns message followed by
```
terminal.js:8410 WebSocket is already in CLOSING or CLOSED state.
```

This happens when pasting in a large block while Powershell starts, before it has had time to display it's prompt.

I've verified that none of this takes case when running powershell in another terminal.

In some extreme cases powershell stops rendering any colors when entering text on the next line. In this specific case when pressing return nothing is executed and nothing is in history. This is not easily reproducible yet alas.

**Comment by PerBothner** [comment]
I think you must be running an old version of domterm - those line numbers don't make sense.

(Also, `pwsh` isn't in the PATH - but `powershell.exe` works.)

**Comment by lypanov** [comment]
Ah your parenthesis explains why you might not be able to reproduce. I'm running the linux version of powershell - https://docs.microsoft.com/en-US/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7

Why the line numbers don't make sense I can't really explain. I didn't see much in your commit history that could fix such issues and by merging with master I've confirmed it, the bugs are present there also.

**Comment by PerBothner** [comment]
Just as a sanity check: `echo $DOMTERM` yields a string starting with `version=2.1.0`?

Also, the `domterm status` command prints out lots of useful information, I would expect it to start with:

    DomTerm version 2.1.0 (git describe: 2.1-0-gbcf1408)
    Copyright 2020 Per Bothner and others

**Comment by lypanov** [comment]
Could it be the Electron version? I'm running Electron 7.1.7 installed via the Windows installer.

**Comment by PerBothner** [comment]
I wondered if at least some of the problems (and the reason I wasn't seeing them) were timing-related, and was able to reproduce some of the symptoms by forcing a delay (by setting `DomTerm._extraDelayForTesting` to 600).

I found one bug (in `Terminal.prototype._removeInputLine`) and a tentative fix but there is at least one more bug that I'll look at in the morning.

**Comment by PerBothner** [comment]
Could you pull the latest version and see if things are improved?

**Comment by lypanov** [comment]
Still happening alas. 

The current stacktrace:

```
terminal.js:7034 Uncaught TypeError: Cannot read property 'insertBefore' of null
    at Terminal.insertNode (terminal.js:7034)
    at Terminal.insertRawOutput (terminal.js:6998)
    at Terminal.editorInsertString (terminal.js:9149)
    at Terminal.pasteText (terminal.js:7237)
    at HTMLDivElement.<anonymous> (terminal.js:3250)
    at Object.DomTerm.doPaste (terminal.js:7288)
    at commands.js:126
    at Object.DomTerm.handleKey (terminal.js:7847)
    at Terminal.keyDownHandler (terminal.js:7933)
    at HTMLDivElement.<anonymous> (terminal.js:3212)
```

**Comment by PerBothner** [comment]
I tweaked the change in `Terminal.prototype._removeInputLine`.  That should fix the worst problems.

Not quite sure I understand what is going on; will ponder more tomorrow.

**Comment by PerBothner** [comment]
Let me know how things work now.

**Comment by lypanov** [comment]
This has fixed the regression of alot in DomTerm. The issues with powershell is also still resolved. Still seeing issues with background colors in alot (the selection leaves trails). Still seeing random alignment issues with text in the window frame (first half of the top line of alot is outside the frame).

**Comment by PerBothner** [comment]
Can you give me detailed instructions on how to reproduce the remaining rendering issues?  Which platform (OS/desktop) are you using? I'm mostly using Fedora 31, but I can also boot into Windows/WSL for testing.

**Comment by lypanov** [comment]
Using Electron/WSL. To reproduce the selection trails in alot I open my message list and move down in the list past the 4th item. The first few items work, but after that the background color drags behind leaving me unsure which item is currently selected.

The alignment issue alas is more difficult to reproduce. I see this on opening messages for example in alot, but, not every time. And in powershell I can't recall having seen it. Once having "broken" the alignment it doesn't repair itself, it looks like the top few pixels are missing (so the very top pixel of a t for example), but honestly I don't really get how it could have ever fit, the line heights seem equal for all lines and the bottom lines cursor is touching the bottom of the frame!

I should add that I'm using a weird font: TT2020 Style E: https://ctrlcctrlv.github.io/TT2020/

**Comment by PerBothner** [comment]
I'm tempted to blame Electron (or the underlying Chromium) and/or the font.  Especially if things work fine on Firefox (or a regular Chrone browser) and/or using a standard font.

Which version of Electron are you using? Maybe try a newer (or possibly an older) version of Electron, in case it a bug that has been fixed (or newly introduced).

I can't think of anything DomTerm does that would chop off the top few pixels of a character.  Possibly relevant: If you set up shell integration, it adds a border and a compensating negative-width margin at the top of a command group. Also wide characters (such as Emoji) have their width and height adjusted.  Otherwise, layout and rendering is handled by the browser (controlled by CSS of course).

You might find it instructive to Toggle Developer Tools (in View menu or type Ctr-Shift-I) and select Elements. Each line (or group of lines) is a `<div class="domterm-pre">`.  You can play with the Styles, enabling or disabling style elements (including fonts) to see if it makes a difference.

Unlike some other browser-based terminals, DomTerm does not render the selection itself, using the browser's standard selection. It may use the JS Selection API to change which characters are selected. So if you see rendering errors in the  selection (such as fractional characters selected) that is a browser/Electron/font bug.  If the wrong characters are selected, that could well be a DomTerm bug.

An experiment to consider is adding this to your `settings.ini`:

     style.caret = blinking-bar
 
This uses a different mechanism to display the caret (text cursor) - which may work better or worse than the default `blinking-block`, depending on the browser.  (Both work fine for me.)
